export const dummyData = [
  {
    id: 1,
    name: 'lorem ipsum',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    price: 32,
    size: 'Medium',
    for: 'men',
    highlight: true,
    inStock: true,
    img: 'https://images.pexels.com/photos/1342609/pexels-photo-1342609.jpeg?auto=compress&cs=tinysrgb&w=1600',
  },
  {
    img: 'https://images.pexels.com/photos/937481/pexels-photo-937481.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 2,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    price: 32,
    inStock: true,
    for: 'men',
  },
  {
    img: 'https://images.pexels.com/photos/1096849/pexels-photo-1096849.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 3,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1300550/pexels-photo-1300550.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 4,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/38270/son-in-law-cufflinks-black-and-white-bow-tie-38270.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 5,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1661416/pexels-photo-1661416.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 6,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    highlight: true,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1416971/pexels-photo-1416971.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 7,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/63196/pexels-photo-63196.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 8,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/447186/pexels-photo-447186.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 9,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
    trending: true,
  },
  {
    img: 'https://images.pexels.com/photos/605208/pexels-photo-605208.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 10,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'men',
    price: 32,
    inStock: true,
  },
  {
    id: 11,
    name: 'lorem ipsum',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    price: 32,
    size: 'Medium',
    for: 'women',
    inStock: true,
    img: 'https://images.pexels.com/photos/1078958/pexels-photo-1078958.jpeg?auto=compress&cs=tinysrgb&w=1600',
  },
  {
    img: 'https://images.pexels.com/photos/1755428/pexels-photo-1755428.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 12,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    price: 32,
    trending: true,
    inStock: true,
    for: 'women',
  },
  {
    img: 'https://images.pexels.com/photos/2235071/pexels-photo-2235071.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 13,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2065195/pexels-photo-2065195.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 14,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/902030/pexels-photo-902030.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 15,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    trending: true,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1020052/pexels-photo-1020052.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 16,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/904117/pexels-photo-904117.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 17,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/859195/pexels-photo-859195.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 18,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/884979/pexels-photo-884979.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 19,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1566435/pexels-photo-1566435.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 20,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'women',
    price: 32,
    trending: true,
    inStock: true,
  },

  {
    id: 21,
    name: 'lorem ipsum',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    price: 32,
    size: 'Medium',
    for: 'electronics',
    inStock: true,
    img: 'https://images.pexels.com/photos/325153/pexels-photo-325153.jpeg?auto=compress&cs=tinysrgb&w=1600',
  },
  {
    img: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 22,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    price: 32,
    inStock: true,
    for: 'electronics',
  },
  {
    img: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 23,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/132700/pexels-photo-132700.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 24,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2136243/pexels-photo-2136243.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 25,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1432675/pexels-photo-1432675.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 26,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/744366/pexels-photo-744366.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 27,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    trending: true,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 28,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/163073/raspberry-pi-computer-linux-163073.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 29,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 30,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'electronics',
    price: 32,
    inStock: true,
  },
  {
    id: 31,
    name: 'lorem ipsum',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    price: 32,
    size: 'Medium',
    for: 'jewelry',
    inStock: true,
    img: 'https://images.pexels.com/photos/1458867/pexels-photo-1458867.jpeg?auto=compress&cs=tinysrgb&w=1600',
  },
  {
    img: 'https://images.pexels.com/photos/691046/pexels-photo-691046.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 32,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    price: 32,
    highlight: true,
    inStock: true,
    for: 'jewelry',
  },
  {
    img: 'https://images.pexels.com/photos/1413420/pexels-photo-1413420.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 33,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1453008/pexels-photo-1453008.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 34,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/998521/pexels-photo-998521.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 35,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1302307/pexels-photo-1302307.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 36,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/3266700/pexels-photo-3266700.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 37,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1395305/pexels-photo-1395305.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 38,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/859895/pexels-photo-859895.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 39,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    highlight: true,
    for: 'jewelry',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2537930/pexels-photo-2537930.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 40,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    id: 41,
    name: 'lorem ipsum',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    price: 32,
    size: 'Medium',
    for: 'beauty',
    trending: true,

    inStock: true,
    img: 'https://images.pexels.com/photos/2866796/pexels-photo-2866796.jpeg?auto=compress&cs=tinysrgb&w=1600',
  },
  {
    img: 'https://images.pexels.com/photos/2622187/pexels-photo-2622187.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 42,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    price: 32,
    inStock: true,
    for: 'beauty',
  },
  {
    img: 'https://images.pexels.com/photos/2639947/pexels-photo-2639947.jpeg?auto=compress&cs=tinysrgb&w=1600a',
    id: 43,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2720447/pexels-photo-2720447.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 44,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2732197/pexels-photo-2732197.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 45,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/3517928/pexels-photo-3517928.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 46,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    highlight: true,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2587370/pexels-photo-2587370.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 47,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/3373740/pexels-photo-3373740.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 48,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1749452/pexels-photo-1749452.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 49,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',

    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/279480/pexels-photo-279480.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 50,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'beauty',
    price: 32,
    inStock: true,
  },
  {
    id: 51,
    name: 'lorem ipsum',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    price: 32,
    size: 'Medium',
    for: 'kitchen',
    inStock: true,
    img: 'https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1600',
  },
  {
    img: 'https://images.pexels.com/photos/2724748/pexels-photo-2724748.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 52,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    price: 32,
    inStock: true,
    trending: true,
    for: 'kitchen',
  },
  {
    img: 'https://images.pexels.com/photos/1070880/pexels-photo-1070880.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 53,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'kitchen',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/2089698/pexels-photo-2089698.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 54,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    highlight: true,
    for: 'kitchen',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1435895/pexels-photo-1435895.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 55,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'kitchen',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/3637739/pexels-photo-3637739.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 56,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'kitchen',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/952366/pexels-photo-952366.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 57,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    highlight: true,
    for: 'kitchen',
    price: 32,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/1087909/pexels-photo-1087909.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 58,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'kitchen',
    price: 32,
    trending: true,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/244395/pexels-photo-244395.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 59,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'kitchen',
    price: 32,
    highlight: true,
    inStock: true,
  },
  {
    img: 'https://images.pexels.com/photos/12653183/pexels-photo-12653183.jpeg?auto=compress&cs=tinysrgb&w=1600',
    id: 60,
    trending: true,
    name: 'Basic Tee',
    description:
      'orem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ',
    size: 'Large',
    for: 'kitchen',
    price: 32,
    inStock: true,
  },
];
