import { Divider } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState, useEffect } from 'react';
import CategoryHeader from '../../components/CategoryHeader';
import Footer from '../../components/Footer';
import Header from '../../components/Header';

function CategoryPage() {
  const router = useRouter();
  const [ifUserSearchPrice, setIfUserSearchPrice] = useState(false);
  const [currentCheckPrice, setCurrentCheckPrice] = useState('');
  const onChangeAttribute = (value) => {
    console.log(value);
    // setCheckBoxChecked(value);
  };
  useEffect(() => {
    if (ifUserSearchPrice.length < 0) {
      setIfUserSearchPrice((prev) => !prev);
    }
  }, [ifUserSearchPrice]);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" text-white  ">
        <Header imageURL="/logowithrmbg.png" />
        <CategoryHeader />
        <Divider className="bg-gray-500 pt-[0.4px]" />
      </div>
      <div className="px-10 py-10">
        <div className="mb-5">
          <h1 className="font-semibold text-5xl mb-5">{router.query.id}</h1>
          <p className="w-[50%] text-lg">
            Check out our new latest arrival, Lorem, ipsum dolor sit amet
            consectetur adipisicing elit. Provident aliquid libero quidem quasi
            necessitatibus quod inventore cupiditate dolore porro voluptatibus.
          </p>
        </div>
        <Divider className="bg-gray-500 pt-[0.4px] " />
        <div>
          <div className="flex justify-between px-10 pt-10">
            <h1 className="font-semibold text-xl">What you looking for?</h1>
            <div>
              <h1>Sort by</h1>
            </div>
          </div>
          <div className="flex px-10 py-10">
            <div className="flex-[0.4] tracking-wide">
              <div>
                {/* <h1 className="py-2 ">Price Range</h1> */}
                <div className="flex gap-2 text-sm mb-2">
                  <input
                    type="checkbox"
                    name="belowandabove"
                    id="below50"
                    onClick={(e) => {
                      if (currentCheckPrice === 'below50') {
                        setCurrentCheckPrice('');
                      } else {
                        setCurrentCheckPrice(e.target.id);
                      }
                    }}
                    checked={currentCheckPrice === 'below50'}
                    disabled={ifUserSearchPrice}
                  />
                  <label htmlFor="below50">Below $50</label>
                </div>
                <div className="flex gap-2  text-sm mb-2">
                  <input
                    type="checkbox"
                    name="belowandabove"
                    onClick={(e) => {
                      if (currentCheckPrice === 'above50') {
                        setCurrentCheckPrice('');
                      } else {
                        setCurrentCheckPrice(e.target.id);
                      }
                    }}
                    checked={currentCheckPrice === 'above50'}
                    id="above50"
                    disabled={ifUserSearchPrice}
                  />
                  <label htmlFor="above50">Above $50</label>
                </div>
                <div className="flex gap-2 mb-2">
                  <input
                    type="number"
                    name="entervalue"
                    className="w-[30%] px-5 py-1 outline-none border tracking-wide"
                    placeholder="Price range..."
                    onChange={(e) => {
                      setIfUserSearchPrice(e.target.value);
                    }}
                    id=""
                  />
                  <button className="border px-2 bg-gray-100">Go</button>
                </div>
                <div className="flex gap-2  text-sm mb-2">
                  <input type="checkbox" name="newarrival" id="" />
                  <label htmlFor="newarrival">New Arrival</label>
                </div>
              </div>
            </div>
            <div className="flex-1">123</div>
          </div>
        </div>
      </div>
      <div>
        <Footer />
      </div>
    </div>
  );
}

export default CategoryPage;
