import Head from 'next/head';
import React from 'react';
import CategoryHeader from '../components/CategoryHeader';
import Header from '../components/Header';
import { Divider } from '@chakra-ui/react';
import Footer from '../components/Footer';
import CartContainer from '../components/CartContainer';

//Was created in 07/11/2022 Monday
function cart() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" text-white  ">
        <Header />
        <CategoryHeader />
        <Divider className="bg-gray-500 pt-[0.4px]" />
      </div>
      <div>
        <CartContainer />
      </div>
      <div className="">
        <Footer />
      </div>
    </div>
  );
}

export default cart;
