import { Divider } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';
import CategoryHeader from '../components/CategoryHeader';
import Footer from '../components/Footer';
import Header from '../components/Header';

function ShopNow() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" text-white  ">
        <Header />
        <CategoryHeader />
        <Divider className="bg-gray-500 pt-[0.4px]" />
      </div>
      <div>
        <div></div>
      </div>
      <div>
        <Footer />
      </div>
    </div>
  );
}

export default ShopNow;
